ci:
  autoupdate_schedule: quarterly
  skip: [pip-compile]
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.2
    hooks:
      - id: ruff-check
      - id: ruff-format
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.19
    hooks:
      - id: pip-compile
        name: pip-compile requirements_base.in
        args: [requirements_base.in, -o, requirements_base.txt]
        files: ^requirements_base\.(in|txt)$
      - id: pip-compile
        name: pip-compile requirements.in
        args: [requirements.in, -o, requirements.txt]
        files: ^requirements(_base)?\.(in|txt)$
      - id: pip-compile
        name: pip-compile requirements_dev.in
        args: [requirements_dev.in, -o, requirements_dev.txt]
        files: ^requirements(_base|_dev)?\.(in|txt)$
