name: Translations
on:
  pull_request: {}
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install translate-toolkit for pocount
        run: |
          sudo apt update
          sudo apt install translate-toolkit
      - run: pip install -r requirements.txt
      - run: python manage.py makemessages -l es
      - name: Count incomplete translations
        run: |
          output=$(find . -name LC_MESSAGES -not -path "*/en/*" -exec pocount --incomplete --short "{}" +)
          echo $output
          [ "$output" = "" ]
