name: Translations
on:
  pull_request: {}
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip
          cache-dependency-path: '**/requirements*.txt'
      - name: Install translate-toolkit
        run: |
          sudo apt update
          sudo apt install gettext translate-toolkit
      - run: pip install -r requirements.txt
      - run: python manage.py makemessages -a
      - name: Count incomplete translations
        shell: bash
        run: |
          output=$(find . -name LC_MESSAGES -not -path "*/en_US/*" -exec pocount --incomplete --short "{}" +)
          echo $output
          [ "$output" = "" ]
