name: Translations
on:
  pull_request: {}
  push:
    branches: [main]
jobs:
  i18n:
    uses: open-contracting/.github/.github/workflows/i18n-django.yml@main
    with:
      source: en_US
      python-version: {{ cookiecutter.python_version }}
