name: Translations
on:
  pull_request: {}
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/cache@v2
        with:
          {%- raw %}
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt', 'setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-
          {%- endraw %}
      - name: Install translate-toolkit
        run: |
          sudo apt update
          sudo apt install gettext translate-toolkit
      - run: pip install -r requirements.txt
      - run: python manage.py makemessages -a
      - name: Count incomplete translations
        run: |
          output=$(find . -name LC_MESSAGES -not -path "*/en_US/*" -exec pocount --incomplete --short "{}" +)
          echo $output
          [ "$output" = "" ]
